quarkus.datasource.db-kind = postgresql

quarkus.rest-client.situacao-cadastral-api.url=${QUARKUS_CLIENT_HTTP}
quarkus.datasource.username = ${QUARKUS_DATASOURCE_USERNAME}
quarkus.datasource.password = ${QUARKUS_DATASOURCE_PASSWORD}
quarkus.datasource.jbdc.url=jbdc:postgresql://${QUARKUS_DATASOURCE_HOST}

# quarkus.rest-client.situacao-cadastral-api.url=http://localhost:8181
# quarkus.datasource.username=admin
# quarkus.datasource.password=123456
# quarkus.datasource.jbdc.url=jbdc:postgresql://localhost:5432/banco_db
quarkus.hibernate-orm.database.generation=drop-and-create 
# quarkus.hibernate-orm.database.generation=none # com as migratyins


# quarkus.hibernate-orm.sql-load-script=no-file
# quarkus.hibernate-orm.database.generation=none

